# Generated by Django 4.1.4 on 2022-12-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bankapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="branches", options={},),
        migrations.AlterField(
            model_name="branches",
            name="image",
            field=models.ImageField(blank=True, upload_to="branches"),
        ),
    ]
