# Generated by Django 4.1.4 on 2022-12-19 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bankapp", "0002_alter_branches_options_alter_branches_image"),
    ]

    operations = [
        migrations.DeleteModel(name="Branches",),
    ]
